language: python
python:
- 2.6
- 2.7
- 3.3
- 3.5
install:
- pip install coveralls pyside
script:
- python run_tests.py
- pip install git+git://github.com/pyblish/pyblish-lite.git
after_success:
- coveralls
